<?php
/** @var \Strativ\ProductTags\Block\ProductTags $block */
$tags = $block->getProductTags();
if ($tags):
?>
    <div class="product-tags">
        <strong><?php echo __('Tags:'); ?></strong>
        <?php foreach ($tags as $tag): ?>
            <a href="<?php echo $this->escapeHtml($block->getUrl('producttags/tag/' . urlencode($tag))); ?>" class="tag"><?php echo $this->escapeHtml($tag); ?></a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>